### PR TITLE
Remove FluentLayout classes

### LINKED ISSUE #32: Deprecate all FluentLayout classes

### PR DESCRIPTION
**Pull request by 1nk0gn1to**
Closes #32

### CODE REVIEW

**Comment by evgenyvalavin** [comment]
@1nk0gn1to PR needs to be nice and shiny. Link an Issue to the PR

**Comment by evgenyvalavin** [comment]
The PR is about deprecating or removing FluentLayout?

**Comment by 1nk0gn1to** [comment]
@evgenyvalavin This PR is about removing FluentLayout

**Comment by evgenyvalavin** [comment]
> @evgenyvalavin This PR is about removing FluentLayout

Good!
Then we should change the PR name to: "Remove FluentLayout classes" to make it clear

**Comment by 1nk0gn1to** [comment]
Done!

**Comment by evgenyvalavin** [comment]
> @1nk0gn1to PR needs to be nice and shiny. Link an Issue to the PR

@1nk0gn1to almost ready to close the PR. Linking an issue is the last step
image

**Comment by 1nk0gn1to** [comment]
image
@evgenyvalavin I no have this gear

**Comment by 1nk0gn1to** [comment]
@evgenyvalavin I found a way to add issue!

**Review by evgenyvalavin — APPROVED** [review]

**Pull request merged**
